// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenGitHub() {
  return window['go']['main']['App']['OpenGitHub']();
}

export function SelectFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2, arg3);
}

export function StartCustomScan(arg1) {
  return window['go']['main']['App']['StartCustomScan'](arg1);
}

export function StartDiscoverColos() {
  return window['go']['main']['App']['StartDiscoverColos']();
}

export function StartQuickScan(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartQuickScan'](arg1, arg2, arg3);
}

export function StartTestIPs(arg1) {
  return window['go']['main']['App']['StartTestIPs'](arg1);
}
