// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelScan():Promise<void>;

export function CopyToClipboard(arg1:string):Promise<boolean>;

export function GetVersion():Promise<string>;

export function OpenGitHub():Promise<void>;

export function SelectFile(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function StartCustomScan(arg1:main.CustomScanConfig):Promise<string>;

export function StartDiscoverColos():Promise<string>;

export function StartQuickScan(arg1:number,arg2:number,arg3:number):Promise<string>;

export function StartTestIPs(arg1:string):Promise<string>;
